spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasksdb
    username: root
    password: Ben@24
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect